# Generated by Django 4.0 on 2021-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('seller', models.CharField(blank=True, max_length=255, null=True)),
                ('epoch_timestamp', models.IntegerField(blank=True, null=True)),
                ('price_unit_dollar', models.FloatField(blank=True, null=True)),
                ('price_unit_jewel', models.FloatField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_gasfee', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auctions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('to_wallet', models.CharField(max_length=255)),
                ('from_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('epoch_timestamp', models.IntegerField()),
                ('price_unit_dollar', models.FloatField()),
                ('price_unit_jewel', models.FloatField(blank=True, null=True)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('transaction_gasfee', models.FloatField(blank=True, null=True)),
                ('auction_id', models.IntegerField(blank=True, null=True)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('quest_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField()),
                ('to_wallet', models.CharField(max_length=255)),
                ('from_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('epoch_timestamp', models.IntegerField()),
                ('price_unit_dollar', models.FloatField()),
                ('price_unit_jewel', models.FloatField(blank=True, null=True)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('transaction_gasfee', models.FloatField(blank=True, null=True)),
                ('auction_id', models.IntegerField(blank=True, null=True)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('quest_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quests_test',
                'managed': False,
            },
        ),
    ]
